baseURL = 'http://127.0.0.1/'
languageCode = 'ja'
title = 'OCIチュートリアル'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

geekdocRepo = "https://github.com/thegeeklab/hugo"

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
  customCSS = ["./custom.css"]
  favicon = "./img/favicon.ico"
  geekdocLogo = "./img/oracle_favicon.png"
  geekdocMenuBundle = true
  geekdocPageLastmod = true
  geekdocTagsToMenu = true
  geekdocBackToTop = true                    # topへ戻るボタン
  geekdocSearch = true
  geekdocSearchShowParent = true

[params.geekdocContentLicense]
  name = "日本オラクル株式会社"
  link = "https://www.oracle.com/jp/"